[tool.poetry]
name = "raspbernetes"
version = "0.1.0"
description = "Manage Kubernetes on a Raspberry Pi cluster"
authors = ["Lee Myring <mail@thinkstack.io>"]
readme = "README.md"
license = "MIT"

[tool.poetry.dependencies]
ansible = "2.9.9"
jinja2 = "^2.11"
python = "^3.8"
pyyaml = "*"

[tool.poetry.dev-dependencies]
bandit = "*"
flake8 = "*"
pre-commit = "^2.4.0"
pytest = "^5.3.5"
pytest-cov = "^2.9.0"
pytest-pycodestyle = "^2.0.0"
pytest-black = "^0.3.8"
reorder-python-imports = "^2.3.0"
safety = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
