[tool.poetry]
name = "raspbernetes"
version = "0.1.0"
description = "Manage Kubernetes on a Raspberry Pi cluster"
authors = ["Lee Myring <mail@thinkstack.io>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
ansible = "2.9.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
