---
- name: "List all known variables and facts"
  debug:
    var: hostvars[inventory_hostname]
  when:
    - full_debug == true

- name: "Print specific variables"
  debug:
    msg: |
      The ansible_distribution is {{ ansible_distribution }}
      The ansible_lsb.id is {{ ansible_lsb.id }}
