name: Ansible Lint  # feel free to pick your own name

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Lint Ansible Playbook
        uses: ansible/ansible-lint-action@master
        with:
          targets: "./"
          override-deps: |
            ansible==2.9
            ansible-lint==4.2.0
